---
name: Check code snippets

on:
  pull_request:

jobs:
  snippets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: "pip"
          cache-dependency-path: databuilder/requirements.*.txt

      - uses: extractions/setup-just@v1

      - name: Run dev tooling on snippets
        run: just databuilder/check

      - name: Check snippets work
        run: |
          # extract examples from the snippets, this will also test they are
          # valid examples
          just databuilder/extract

          # check no examples have changed
          git diff --exit-code examples
