---
name: 'Update databuilder docs'

on:
  workflow_dispatch:
    inputs:
      download_url: 
        description: "Download URL for public_docs.json"
        required: true
      branch_tag:
        desription: "Tag to append to the branch name for the new PR"
        required: true

jobs:

  update_docs:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3    
      
      - name: Download release artifact
        run: |
          curl -L ${{ github.event.inputs.download_url }} > public_docs.json

      - name: commit new docs file
        env:
          BRANCH: update-docs-${{ github.event.inputs.branch_tag }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b $BRANCH
          git add public_docs.json
          git commit -m "Update databuilder docs"
          git push origin $BRANCH

      - name: Open PR
        uses: actions/github-script@v6
        env:
          BRANCH: update-docs-${{ github.event.inputs.branch_tag }}
        with:
          script: |
            const { repo, owner } = context.repo;
            const { BRANCH } = process.env;
            result = await github.rest.pulls.create({
              title: 'Update databuilder docs',
              owner,
              repo,
              head: BRANCH,
              base: 'main',
            });
            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number: result.data.number,
              team_reviewers: ['data-team'],
            });
      
      - name: Trigger build-check
        uses: actions/github-script@v6
        env:
          BRANCH: update-docs-${{ github.event.inputs.branch_tag }}
        with:
          script: |
            const { repo, owner } = context.repo;
            const { BRANCH } = process.env;
            await github.rest.actions.createWorkflowDispatch({
              owner: 'opensafely',
              repo: 'documentation',
              workflow_id: 'build.yml',
              ref: BRANCH,
            })
 